<?php 
return array (
  'site_name' => '微专家微营销系统',
  'site_title' => '微信公众平台',
  'site_logo' => 'tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://test.gope.cn/',
  'site_my' => '微营销',
  'server_key' => 'bc9ed510a91c14331cf2f6ce4169807b',
  'server_topdomain' => 'www.gope.cn',
  'connectout' => '用户已到期，请联系管理员或客服充值',
  'ischeckuser' => 'true',
  'reg_needmp' => 'true',
  'open_biz' => '1',
  'isclosekuser' => 'false',
  'server_discuz' => '',
  'reg_groupid' => '4',
  'reg_validdays' => '7',
  'router_key' => '',
  'ipc' => '苏ICP备6958426',
  'site_qq' => '75943938',
  'site_mp' => '12345678912',
  'site_kfqq' => '75943938',
  'site_qqqun' => '75943938',
  'site_tel' => '400-585-8289',
  'site_adress' => '狗扑源码社区',
  'baidu_map_api' => '908bb5a05fa5f839dafeb1a957c7ed51',
  'site_email' => '75943938@qq.com',
  'keyword' => 'PIGCMS,微信公众账号,微信公众平台,微信公众账号开发,微信二次开发,微信接口开发,微信托管服务,微信营销,微信公众平台接口开发',
  'content' => '微信公众平台接口开发、托管、营销活动、二次开发',
  'countsz' => '',
  'copyright' => 'Copyright (c) 2015 微营销系统 版权所有',
  'ucenter_db_set' => '',
  'ucenter_web_set' => '',
);